---
title: 异常
date: 2020-09-25
---

## 1. Java异常概述

清华大学郑莉——

Java中声明了很多异常类，每个异常类都代表了一种运行错误，类中包含了：

1. 运行错误的信息；

2. 处理错误的方法

每当Java程序运行过程中发生一个可识别的运行错误时，即该错误有一个异常类与之相对应时，系统都会产生一个相应的该异常类的对象，即产生一个异常。

Java异常处理机制的优点：

- 将错误处理代码从常规代码中分离出来；
- 按错误类型和差别分组；
- 对无法预测的错误的捕获和处理；
- 克服了传统方法的错误信息有限的问题；
- 把错误传播给调用堆栈。

异常分为检查型异常和非检查型异常，后者并不要求程序必须捕获和处理它（例如数组越界、除零等）。

### 1.1 Java异常类体系

在Java中，异常对象都是派生于`Throwable`类的一个类实例。

所有的异常都是由`Throwable`继承而来，然后紧接着分为两大体系——`Error`和`Exception`：

<img src="https://figure-bed.chua-n.com/Java/40.jpg" alt="40" style="zoom:50%;" />

- Error类层次结构描述了Java运行时系统的内部错误和资源耗尽错误。应用程序中不应该抛出这种类型的异常，如果出现了，程序员几乎无能为力去解决。
- Exception类是设计Java程序时要重点关注的，该分支又可分为两大分支：一个派生于`RuntimeException`，另一个分支包含其他异常。一般规则是，由编程错误导致的异常属性`RuntimeException`；如果程序本身没有问题，但由于像I/O错误这类问题导致的异常属于其他异常。

Java语言规范将派生于`Error`类或`RuntimeException`类的所有异常称为**非检查型**（unchecked）异常，所有其他的异常称为**检查型**（checked）异常。编译器将检查你是否为所有的检查型异常提供了异常处理器。

- 如果一个方法有可能抛出检查型异常，那么必须在方法的首部列出所有可能的异常类：

    ```java
    public Image loadImage(String s) throws FileNotFoundException, EOFException {
        // ...
    }
    ```

- 对于非检查型异常，任何程序代码都有可能抛出，程序员对此完全无法控制，因此不需要在方法中声明。

所有`Throwable`的子类在构造器中都可以接收一个`cause`对象作为参数，用来表示原始异常，这样可以把原始异常传递给新的异常，使得即使在当前位置创建并抛出了新的异常，也能通过这个异常链追踪到异常最初发生的位置。

### 1.2 异常类的方法

所有的异常对象都包含了如下几个常用方法：

| 方法                              | 作用                                   |
| --------------------------------- | -------------------------------------- |
| `getMessage()`                    | 返回该异常的详细描述字符串             |
| `printStackTrace()`               | 将该异常的跟踪栈信息输出到标准错误输出 |
| `printStackTrace(PrintStream  s)` | 将该异常的跟踪栈信息输出到指定输出流   |
| `getStackTrace()`                 | 返回该异常的跟踪栈信息                 |

### 1.3 自定义异常类

自定义异常时，应该定义一个派生于`Exception`或其子类的类，如IOException。

定义异常类时通常需要提供两个构造器：

1. 一个无参数的构造器；

2. 一个带一个字符串参数的构造器，这个字符串将作为该异常对象的描述信息（也就是异常对象的`getMessage()`方法的返回值）。因为超类`Throwable`的`toString`方法会返回一个字符串，其中包含这个详细信息，这在调试中非常有用。

    ```java
    class AuctionException extends Exception {
        public AuctionException() {
        }
        
        public AuctionException(String msg) {
            super(msg);
        }
    }
    ```

## 2. try语句块

Java异常处理机制的语法结构：

```java
try {
    // ...
} catch (SubException1 e) {
    // ...
} catch (SubException2 e){
    // ...
}
// ...
finally{
    // ...
}
```

- try块与if/switch语句不一样，try块与catch块后的花括号{}永远不可省略；

- 一个catch块还可以捕获多种类型的异常，此时：
    
    - 多种异常类型之间用竖线（|）隔开；
    - 异常变量有隐式的final修饰，因此程序不能对异常变量重新赋值；
    - 捕获多个异常不仅会让你的代码看起来更简单，还会更高效。生成的字节码只包含对应公共catch子句的一个代码块。
    
    ```java
    class MultiExceptionTest {
        public static void main(String[] args) {
            try {
                int a = Integer.parseInt(args[0]);
                int b = Integer.parseInt(args[1]);
                int c = a / b;
            } catch (IndexOutOfBoundsException | NumberFormatException | ArithmeticException ie) {
                System.out.println("程序发生了数组越界、数字格式异常、算法异常之一");
                // 捕获多异常时，异常变量默认有final修饰，故下行错误
                ie = new ArithmeticException("test");
            } catch (Exception e) {
                System.out.println("未知异常");
                // 捕获一种类型的异常时，异常变量没有final修饰，故下行正确
                e = new RuntimeException("test");
            }
        }
    }
    ```
    
- 对于finally块，其总会被执行，牢记这句话！

    - 即便try/catch块存在return/throw语句，finally块也会执行，当finally块执行完成后，系统才会再次跳回来执行try/catch块中的相应语句。
    - 当finally子句包含return语句时，有可能产生意想不到的结果——假设利用return语句从try语句块中间退出，在方法返回前，会执行finally子句块，如果finally块也有一个return语句，这个返回值将会遮蔽原来的返回值。
    - 一个需要额外强调的情况是，如果在finally块执行前使用`System.exit(1)`退出了虚拟机，则finally块将失去执行的机会。
    - 由上，为避免复杂的流程，不要把改变控制流的语句（`return, throw, break, continue`）放在finally子句中。


进行异常捕获时，应遵循这样的规则：把Exception类对应的catch块放在最后，而且所有父类异常的catch块都应该排在子类异常catch块的后面，否则将出现编译错误。

## 3. 关闭物理资源

有时程序在try块里打开了一些物理资源，如数据库连接、网络连接、磁盘文件等，这些物理资源都必须显式回收，通常在finally块中进行回收。

try关键字后可紧一对**圆括号**，圆括号可以声明、初始化一个或多个物理资源，try语句在该语句结束时自动关闭这些资源。此时要求这些资源实现类必须实现`AutoCloseable`或`Closeable`接口，实现这两个接口就必须实现`close()`方法。

```java
class AutoCloseTest {
    public static void main(String[] args) throws IOException {
        try (
            // 声明、初始化两个可关闭的资源
            // try语句会自动关闭这两个资源
            BufferedReader br = new BufferedReader(new FileReader("AutoCloseTest.java"));
            PrintStream ps = new PrintStream(new FileOutputStream("a.txt"))) {
            // 使用两个资源
            System.out.println(br.readLine());
            ps.println("庄生晓梦迷蝴蝶");
        }
    }
}
```

Java 9再次增强了这种try语句，Java 9不要求在try后的圆括号内声明并创建资源，只需要自动关闭的资源有final修饰或者是effectively final，Java 9允许将资源变量放在try后的圆括号内。

```java
class AutoCloseTest2 {
    public static void main(String[] args) throws IOException {
        // 有final修饰的资源
        final BufferedReader br = new BufferedReader(new FileReader("AutoCloseTest.java"));
        // 没有显式使用final修饰，但只要不对该变量重新赋值，该变量就是effectively final的
        PrintStream ps = new PrintStream(new FileOutputStream("a.txt"));
        // 只要将两个资源放在try后的圆括号内即可
        try (br; ps) {
            // 使用两个资源
            System.out.println(br.readLine());
            ps.println("庄生晓梦迷蝴蝶");
        }
    }
}
```

## 4. throws/throw

thorws关键字在方法签名中使用，用于声明该方法可能抛出的异常；throw关键字用于抛出一个实际的异常，throw可以单独作为语句使用，抛出一个具体的异常对象。

### 4.1 使用throws抛出异常

```java
throws ExceptionClass1, ExceptionClass2…
```

throws意味着当前方法不知道如何处理这种类型的异常，将该异常交由上一级调用者处理；

当main方法使用了throws声明抛出异常时，该异常将交由JVM处理。JVM对异常的处理方法是：打印异常的跟踪栈信息，并中止程序运行。

```java
class ThrowsTest {
    // main方法声明不处理IOException异常，将该异常交由JVM处理
    public static void main(String[] args) throws IOException {
        FileInputStream fis = new FileInputStream("a.txt");
    }
}
```

但是，如果某段代码中调用了一个带throws声明的方法，该方法声明抛出了Checked异常，则表明该方法希望它的调用者来处理该异常。即，调用该方法时要么放在try块中显式捕获该异常，要么放在另一个带throws声明抛出的方法中。

```java
class ThrowsTest {
    public static void main(String[] args) throws Exception {
        // 因为test()方法声明抛出IOException异常
        // 所以调用test()方法的代码要么处于try...catch块中，
        // 要么处于另一个带throws声明抛出的方法中
        test();
    }
    public static void test() throws IOException {
        // 因为FileInputStream的构造器声明抛出IOException异常
        // 所以调用FileInputStream的代码要么处于try...catch块中，
        // 要么处于另一个带throws声明抛出的代码中
        FileInputStream fis = new FileInputStream("a.txt");
    }
}
```

**方法重写时使用throws声明抛出异常有一个限制**：子类方法声明抛出的异常类型应该是父类方法声明抛出的异常类型的子类或相同，子类方法声明抛出的异常不允许比父类方法声明抛出的异常多。

```java
class OverrideThrows {
    public void test() throws IOException {
        FileInputStream fis = new FileInputStream("a.txt");
    }
}
class Sub extends OverrideThrows {
    // 下面方法出错
    public void test() throws Exception {
    }
}
```

### 4.2 使用throw抛出异常

```java
throw exceptionInstance;
```

throw语句可在程序中主动抛出异常，throw语句抛出的不是异常类，而是一个异常实例，且每次只能抛出一个异常实例；

catch和throw结合使用的情况在大型企业级应用中非常常用，企业级应用对异常的处理通常分成两个部分：①应用后台需要通过日志来记录异常发生的详细情况；②应用还需要根据异常向应用使用者传达某种提示。故而，所有异常都需要这两个方法共同完成。

## 5. 异常链

真实的企业级应用，常常有严格的分层关系，上层功能的实现严格依赖于下层的API，也不会跨层访问。

<img src="https://figure-bed.chua-n.com/Java/41.jpg" alt="41" style="zoom:67%;" />

> 对一个上图所示结构的应用，当业务逻辑层访问持久层出现SQLException异常时，程序不应该把底层的SQLException异常传到用户界面：
>
> 1. 对于正常用户而言，他们不想看到底层SQLException异常，SQLException异常对他们使用该系统没有任何帮助；
> 2. 对于恶意用户而言，将SQLException异常暴露出来不安全。

把底层的原始异常直接传给用户是一种不负责任的表现，通常的做法是：程序先捕获原始异常，然后抛出一个新的业务异常，新的业务异常中包含了对用户的提示信息，这种处理方式被称为**异常转译**。

异常转译可以保证底层异常不会扩散到表现层，避免向上暴露太多的实现细节。这种捕获一个异常然后抛出另一个异常，并把原始异常信息保存下来是一种典型的链式处理（23种设计模式之一：职责链模式），也被称为**异常链**。

所有Throwable的子类在构造器中都可以接收一个cause对象作为参数，这个cause就用来表示原始异常，这样可以把原始异常传递给新的异常，使得即使在当前位置创建并抛出了新的异常，也能通过这个异常链追踪到异常最初发生的位置。

## 6. 异常处理规则

不要过度使用异常，过度使用异常主要有两个方面：

1. 把异常和普通错误混淆在一起，不再编写任何错误处理代码，而是以简单地抛出异常来代替所有的错误处理；

2. 使用异常处理来代替流程控制。

异常处理机制的初衷是将不可预期异常的处理代码和正常的业务逻辑处理代码分享，因此绝不要使用异常处理来代替正常的业务逻辑判断。

不要使用过于庞大的try块。

避免使用CatchAll语句，即不要处理程序发生的所有可能异常：`catch (Throwable t){}`

不要忽略捕获到的异常。

## 7. 断言

### 断言的概念

> 断言是一种测试和调试阶段使用的战术性工具；与之不同，日志是一种在程序整个生命周期都可以使用的战略性工具。

断言机制允许在测试期间向代码中插入一些检查，而在生产代码中会自动删除这些检查。Java语言引入了关键字assert，这个关键字有两种形式：

- `assert condition`
- `assert condition: expression`：表达式部分的唯一目的是产生一个消息字符串，`AssertionError`对象并不存储具体的表达式值，因此，以后无法得到这个表达式值。

### 启用和禁用断言

在默认情况下，断言是禁用的，可以在运行程序时用`-enableeassertions`或`-ea`选项启用断言：

```cmd
java -enableassertions MyApp
```

> 需要注意的是，不必重新编译程序来启用或禁用断言。启用或禁用断言是类加载器的功能。禁用断言时，类加载器会去除断言代码，因此，不会降低程序运行的速度。

也可以在某个类或整个包中启用断言，例如：

```java
java -ea:MyClass -ea:com.mycompany.mylib MyApp
```

也可以使用选项 `-disableassertions` 或 `-da` 在某个特定类和包中禁用断言：

```java
java -ea:... -da:MyClass MyApp
```

## 8. 相关类

- `Throwable`
- `StackWalker`
- `StackWalker.StackFrame`
- `StackTraceElement`

