如果线程执行过程中抛出了一个未处理异常，JVM 在结束该线程之前会自动查询是否有对应的`Thread.UncaughtExceptionHandler`对象，若有，则会调用该对象的`uncauhtException(Thread t, Throwable e)`方法来处理该异常。

`Thread.UncaughtExceptionHandler`是 Thread 类的一个静态内部接口，该接口内只有一个方法：

-   `void uncaughtException(Thread t, Throwable e)`：t 代表出现异常的线程，e 代表该线程抛出的异常

Thread 类提供了两个方法来设置异常处理器：

| 方法                                                         | 说明                                         |
| ------------------------------------------------------------ | -------------------------------------------- |
| `static setDefaultUncaughtExceptionHandler(Thread.UncaughtExceptionHandler eh)` | 为该线程类的所有线程实例设置默认的异常处理器 |
| `setUncaughtExceptionHandler(Thread.UncaughtExceptionHandler eh)` | 为指定的线程实例设置异常处理器               |

异常处理器与通过catch捕获异常是不同的——当使用catch捕获异常时，异常不会向上传播给上一级调用者；<font color="red">但使用异常处理器对异常进行处理之后，异常依然会传播给上一级调用者</font>。

```java
class MyExHandler implements Thread.UncaughtExceptionHandler {
    public void uncaughtException(Thread t, Throwable e) {
        System.out.println(t + " 线程出现了异常：" + e);
    }
}

class ExHandler {
    public static void main(String[] args) {
        // 设置主线程的异常处理器
        Thread.currentThread().setUncaughtExceptionHandler(new MyExHandler());
        int a = 5 / 0;
        System.out.println("程序正常结束！");
    }
}
```

